version: '3'

services:

  webpack-babel:
    image: punimeister/webpack-babel
    restart: on-failure
    environment:
      MODE: development
      EP_test1: ./web/src/entry1.js
      EP_test2: ./web/src/entry2.js
      OUTPUT_DIR: ./web/public
      OUTPUT_FILE: '[name].js'
    volumes:
      - .:/app
